apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-greeter-k8s-be-deployment
  labels:
    app: hello-greeter-k8s-be
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-greeter-k8s-be
  template:
    metadata:
      labels:
        app: hello-greeter-k8s-be
    spec:
      containers:
      - name: backend-container
        image: husovschi/hello-greeter-k8s-be
        ports:
          - name: be-port
            containerPort: 8000
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName